FAT2018/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', main, name='main'),
    path('page/<page>', goTo, name="route"),
    path('delete/<object>/<object_id>', delete, name="delete"),
    path('logSystem', logSystem, name="logSystem"),
    path('createModel', createModel, name="create"),
    path('aproveRequest', aproveRequest, name="approve"),
    path('load/<page>/<model_name>/<person_type>', loadData, name="data"),
]

main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

USER_TYPE_CHOICES = (
    (0, 'Jubilado'),
    (1, 'Doctor'),
    (2, 'Profesor'),
    (3, 'Administrador'),
)

DAY_CHOICES = {
    (0, 'Lunes'),
    (1, 'Martes'),
    (2, 'Miercoles'),
    (3, 'Jueves'),
    (4, 'Viernes'),
}

class Person(models.Model):
    user= models.OneToOneField(settings.AUTH_USER_MODEL, 
                                on_delete=models.CASCADE, 
                                related_name="person",
                                related_query_name="person")
    user_type= models.IntegerField(choices=USER_TYPE_CHOICES)

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)
    
    def get_duties(self):
        results= {}
        results['person']= self
        if self.user_type == 0:
            results['appointmets'] = self.appointments
            results['classrooms'] = self.classrooms
        elif self.user_type == 1:
            results['work_day'] = self.work_days
        elif self.user_type == 2:
            results['classrooms'] = self.classrooms
        elif self.user_type == 3:
            results['persons'] = Person.objects.all()
            results['classrooms'] = Classroom.objects.all()
            results['appointments'] = Appointment.objects.all()
            results['rooms'] = Room.objects.all()
            results['person_requests'] = Person_request.objects.all()
        return results

class Room(models.Model):
    name= models.CharField(max_length=30)
    capacity= models.IntegerField()

    def __str__(self):
        return "{} {}".format(self.name, self.capacity)

class Classroom(models.Model):
    name= models.CharField(max_length=30)
    description= models.CharField(max_length=300)
    members= models.ManyToManyField(Person,
                                    related_name="classrooms",
                                    related_query_name="classroom")
    room= models.ForeignKey(Room,
                            on_delete=models.CASCADE,
                            related_name="classrooms",
                            related_query_name="classroom")

    def __str__(self):
        return "{}".format(self.name)

class Classroom_day(models.Model):
    classroom= models.ForeignKey(Classroom,
                                on_delete=models.CASCADE,
                                related_name="classroom_days",
                                related_query_name="classroom_day")
    day= models.IntegerField(choices=DAY_CHOICES)
    hour= models.TimeField()

    def __str__(self):
        return "{} {}".format(self.day, self.classroom)

class Work_day(models.Model):
    person= models.ForeignKey(Person,
                                on_delete=models.CASCADE,
                                related_name="work_days",
                                related_query_name="work_day")
    day= models.DateField()

    def __str__(self):
        return "{} {}".format(self.person, self.day)

class Appointment(models.Model):
    person= models.ForeignKey(Person,
                                on_delete=models.CASCADE,
                                related_name="appointments",
                                related_query_name="appointment")
    hour= models.TimeField()
    authorized= models.BooleanField(default=False)

    def __str__(self):
        return "{} {} {}".format(self.hour, self.authorized, self.person)

class Person_request(models.Model):
    first_name= models.CharField(max_length=30)
    last_name= models.CharField(max_length=30)
    personal_id= models.CharField(max_length=30)
    password= models.CharField(max_length=30)
    email= models.CharField(max_length=30)

    def approved(self):
        new_user = User.objects.create_user(
            first_name=self.first_name,
            last_name=self.last_name,
            username=self.personal_id,
            password=self.password,
            email=self.email
        )
        Person.objects.create(user=new_user, user_type=0)
        self.delete()

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from . import models
from django.db.models import Model
from django.http import HttpResponse, JsonResponse

def main(request):
    results = {}
    results['parallax'] = True
    return render(request, 'main.html', results)

def goTo(request, page):
    if page == 'profile':
        if request.user.is_authenticated:
            user = models.Person.objects.get(user=request.user)
            results = user.get_duties()
            if user.user_type == 0:
                page += '_for_retired'
            elif user.user_type == 1:
                page += '_for_doctor'
            elif user.user_type == 2:
                page += '_for_teacher'
            elif user.user_type == 3:
                page += '_for_admin'
            else:
                return HttpResponse(status=400)
        else:
            return main(request)    
    else:
        results = {}
    return render(request, '{}.html'.format(page), results)

def delete(request, object, object_id):
    if request.user.is_authenticated:
        model = getModel(object)
        if model:
            obj = model.objects.get(id=object_id)
            obj.delete()
            return HttpResponse("1") 
    return HttpResponse(status=400)

def logSystem(request):
    if request.method == "POST":
        username = request.POST.get("personal_id")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return main(request)
    logout(request)
    return goTo(request, 'login')

def createModel(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            if request.POST['model'].endswith("_request"):
                model = getModel(request.POST['model'])
                if model:
                    dic ={}
                    for a in request.POST.keys():
                        if hasattr(model, a):
                            dic[a]=request.POST[a]
                    obj_created = model.objects.create(**dic)
                    return JsonResponse({
                        'acceptable':True,
                        'object_id': obj_created.id
                    })
    return HttpResponse(status=405)

def aproveRequest(request):
    if request.method == "POST":
        if models.Person.objects.get(user=request.user).user_type == 3:
            request_id = request.POST['model_id']
            model = getModel(request.POST['model'])
            if model:
                request_obj = model.objects.get(id=request_id)
                request_obj.approved()
                return HttpResponse({'acceptable':True})
    return HttpResponse(status=405)

def loadData(request, page, model_name, person_type):
    if request.user.is_authenticated:
        model = getModel(model_name)
        print(model)
        if model:
            data = {}
            page = page.replace('%2F', '/')
            if model_name == "Person":
                data['{}s'.format(model_name.lower())] = model.objects.filter(user_type=person_type)
            else: 
                data['{}s'.format(model_name.lower())] = model.objects.all()
            return render(request, '{}.html'.format(page), data)
    return HttpResponse(status=400)

def getModel(model_name):
    if hasattr(models, model_name):
        model = getattr(models, model_name)
        if issubclass(model, Model):
            return model
    return 0

main/templates/classrooms.html
{% extends 'mainBase.html' %}
{% load static %}
{% block imports %}
{% endblock imports %}
{% block title %}
Identificacion
{% endblock title %}  
{% block body %}
<div class="row">
    {% for classroom in classrooms %}
    {% if  1 == 1 %}
    <div class="col s12 xl6">
        <div class="card grey lighten-3">
            <div class="card-content">
                <span class="card-title">{{ classroom.name }}</span>
            </div>
            <ul class="collection">
                <li class="collection-item">
                    Descripcion: {{ classroom.description }}
                </li>
                <li class="collection-item">
                    Duracion: {{ classroom.duration }}
                </li>
                <li class="collection-item">
                    <table>
                        <thead>
                            <tr>
                                <th>Dia</th>
                                <th>Salon</th>
                                <th>Hora de inicio</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for day in classroom.get_classroom_days %}
                            <tr>
                                <td>{{ day.get_day_display }}</td>
                                <td>{{ day.classroom_place.room }}</td>
                                <td>{{ day.start_hour }}</td>
                            </tr>
                            {% endfor %}                            
                        </tbody>
                    </table>    
                </li>
                {% if 1 == 2 %}
                <li class="collection-item">
                    <center>
                        <button class="btn btn-flat red white-text" onclick="confirm_request('{{ classroom.id }}', '{% url 'classrooms' %}')">Unirse</button>
                    </center>
                </li>
                {% else %}
                <li class="collection-item">
                    <center>
                        <h6 class="red-text" >Usted ya esta registrado en una clase en este horario</h6>
                    </center>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

main/templates/profile_for_admin.html
{% extends 'mainBase.html' %}
{% load static %}
{% block imports %}
{% endblock imports %} 
{% block title %}
{% endblock title %} 
{% block navbar %}
{% endblock navbar %}	
{% block body %}
<div class="row">
	<div class="col s3">
		<div class="col s12">
			<div class="card" id="card_classrooms"></div>
		</div>
		<div class="col s12">
			<div class="card" id="card_appointment"></div>
		</div>
		<div class="col s12">
			<div class="card" id="card_rooms"></div>			
		</div>
	</div>
	<div class="col s6">
		<div class="card">
				<div class="card-content">
						<span class="card-title center">Solicitudes</span>
						<div class="card-content grey-text">
							<span class="card-content center">Aqui se encontraran las solicitudes de los usuarios de la pagina</span>
						</div>
					</div>
			<ul class="collapsible">
			{% if person_requests %}
				<li>
					<div class="collapsible-header">Solicitudes de cuentas</div>
					<div class="collapsible-body">
							<table>
								<thead>
									<tr>
										<th>Nombre</th>
										<th>Dni</th>
										<th>email</th>
										<th>tipo de usuario</th>
										<th>Aceptar/Rechazar</th>
									</tr>
								</thead>
								<tbody>
									{% for person_request in person_requests %}
									<tr>
										<td>{{ person_request.first_name }} {{ person_request.last_name }}</td>
										<td>{{ person_request.personal_id }}</td>
										<td>{{ person_request.email }}</td>
										<td>{{ person_request.get_user_type_display }}</td>
										<td>
											<button class="btn btn-flat green-text" onclick="model_and_id('{% url 'approve' %}', 'Person_request', '{{ person_request.id }}')"><i class="material-icons">check</i></button>
											<button class="btn btn-flat red-text"><i class="material-icons">clear</i></button>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
					</div>
				</li>
			{% endif %}
			{% if classroom_requests %}
				{% for classroom_request in classroom_requests %}
				<li>
					<div class="collapsible-header">{{ classroom_request.teacher.user.get_full_name }} ha solicitado una clase</div>
					<div class="collapsible-body">
						<div class="row">	
							<div class="col s12">
								Nombre: {{ classroom_request.name }}
							</div>
							<div class="col s12">
								Descripcion: {{ classroom_request.description }}
							</div>
							<div class="col s12">
								Duracion: {{ classroom_request.duration }}
								<h4>
								
								</h4>
							</div>
							<div class="col s12">
								<table>
									<thead>
									<tr>
										<th>Dia</th>
										<th>Hora</th>
									</tr>
									</thead>
									<tbody>
									{% for classroom_day_request in classroom_request.get_days %}
									<tr>
										<td>{{ classroom_day_request.get_day_display }}</td>
										<td>{{ classroom_day_request.start_hour }}</td>
									</tr>
									{% endfor %}
									</tbody>
								</table>
							</div>
							<div class="col s12">
								<div class="input-field col s12">
									<select id="select_place">
										{% for classroom_place in classroom_places %}
											<option value="{{ classroom_place.id }}">Salon: {{ classroom_place.room }} - capacidad {{ classroom_place.capacity }}</option>
										{% endfor %}	
									</select>
									<label class="black-text">Lugar</label>
								</div>
							</div>
						</div>
						<center>
							<button class="btn btn-flat green-text"><i class="material-icons">check</i>Aceptar</button>
							<button class="btn btn-flat red-text"><i class="material-icons">clear</i>Rechazar</button>
						</center>
					</div>
				</li>
				{% endfor %}
			{% endif %}
			{% if enrolment_teacher_requests %}
			<li>
				<div class="collapsible-header">Solicitudes de unirse a una clase como profesor</div>
				<div class="collapsible-body">
					<table>
						<thead>
							<tr>
								<th>Profesor</th>
								<th>Clase</th>
								<th>Aceptar/Rechazar</th>
							</tr>
						</thead>
						<tbody>
							{% for enrolment_teacher_request in enrolment_teacher_requests %}
							<tr>
								<td>{{ enrolment_teacher_request.person.user.get_full_name }}</td>
								<td>{{ enrolment_teacher_request.classroom.name }}</td>
								<td>
									<button class="btn btn-flat green-text"><i class="material-icons">check</i></button>
									<button class="btn btn-flat red-text"><i class="material-icons">clear</i></button>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</li>
			{% endif %}
			{% if enrolment_student_requests %}
			<li>
				<div class="collapsible-header">Solicitudes de unirse a una clase como alumno</div>
				<div class="collapsible-body">
					<table>
						<thead>
							<tr>
								<th>Alumno</th>
								<th>Clase</th>
								<th>Aceptar/Rechazar</th>
							</tr>
						</thead>
						<tbody>
							{% for enrolment_student_request in enrolment_student_requests %}
							<tr>
								<td>{{ enrolment_student_request.person.user.get_full_name }}</td>
								<td>{{ enrolment_student_request.classroom.name }}</td>
								<td>
									<button class="btn btn-flat green-text"><i class="material-icons">check</i></button>
									<button class="btn btn-flat red-text"><i class="material-icons">clear</i></button>	
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</li>
			{% endif %}
			{% if work_day_request %}
			<li>
				<div class="collapsible-header">Solicitudes de dias de trabajo</div>
				<div class="collapsible-body">
					<table>
						<thead>
							<tr>
								<th>Doctor</th>
								<th>Hora de inicio</th>
								<th>Hora de finalizacion</th>
								<th>Fecha</th>
								<th>Aceptar/Rechazar</th>
							</tr>
						</thead>
						<tbody>
							{% for work_day_request in work_day_request %}
							<tr>
								<td>{{ work_day_request.doctor.user.get_full_name }}</td>
								<td>{{ work_day_request.start_hour }}</td>
								<td>{{ work_day_request.finish_hour }}</td>
								<td>{{ work_day_request.day }}</td>
								<td>
									<button class="btn btn-flat green-text"><i class="material-icons">check</i></button>
									<button class="btn btn-flat red-text"><i class="material-icons">clear</i></button>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</li>
			{% endif %}
			{% if appointment_requests %}
				<li>
					<div class="collapsible-header">Solicitudes de turnos</div>
					<div class="collapsible-body">
						<table>
							<thead>
								<tr>
									<th>Paciente</th>
									<th>Dia</th>
									<th>Hora de atencion</th>
									<th>Doctor</th>
									<th>Aceptar/Rechazar</th>
								</tr>
							</thead>
							<tbody>
								{% for appointment_request in appointment_requests %}
								<tr>
									<td>{{ appointment_request.person.user.get_full_name }}</td>
									<td>{{ appointment_request.work_day.day }}</td>
									<td>{{ appointment_request.time_attendance }}</td>
									<td>{{ appointment_request.work_day.doctor.user.get_full_name }}</td>
									<td>
										<button class="btn btn-flat green-text"><i class="material-icons">check</i></button>
										<button class="btn btn-flat red-text"><i class="material-icons">clear</i></button>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</li>
			{% endif %}
			</ul>
		</div>
	</div>
	<div class="col s3">
		<div class="col s12">
			<div class="card" id="card_teachers"></div>
		</div>
		<div class="col s12">
			<div class="card" id="card_retireds"></div>
		</div>
		<div class="col s12">
			<div class="card" id="card_doctors"></div>
		</div>
	</div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function() {
	load_classrooms();
	load_appointments();
	load_rooms();
	load_teachers();
	load_retireds();
	load_doctors();
});
function load_classrooms(){
	load('{% url 'data' 'profile_for_admin_parts%2Fclassrooms' 'Classroom' '0' %}', 'card_classrooms');
}
function load_appointments(){
	load('{% url 'data' 'profile_for_admin_parts%2Fappointments' 'Appointment' '0' %}', 'card_appointment');
}
function load_rooms(){
	load('{% url 'data' 'profile_for_admin_parts%2Frooms' 'Room' '0' %}', 'card_rooms');
}
function load_teachers(){
	load('{% url 'data' 'profile_for_admin_parts%2Fteachers' 'Person' '1' %}', 'card_teachers');
}
function load_retireds(){
	load('{% url 'data' 'profile_for_admin_parts%2Fretireds' 'Person' '0' %}', 'card_retireds');
}
function load_doctors(){
	load('{% url 'data' 'profile_for_admin_parts%2Fdoctors' 'Person' '1' %}', 'card_doctors');
}
</script>
{% endblock body %}

main/templates/profile_for_admin_parts/appointments.html
<div class="card-content white-text">
    <span class="card-title black-text">Turnos</span>
</div>
{% if appointments %}
<ul class="collapsible">
    {% for appointment in appointments %}
        <li>
          <div class="collapsible-header">{{ appointment.person.user.get_full_name }}-{{ appointment.work_day.day }}</div>
          <div class="collapsible-body">
            <div class="row">
                Doctor: {{ appointment.work_day.doctor.user.get_full_name }}
            </div>
            <div class="row">
                Horario: {{ appointment.time_attendance }}
            </div>
            <center><button class="waves-effect waves-light red btn"><i class="material-icons right">delete</i>Eliminar</button></center>
          </div>
        </li>
        {% endfor %}
    </ul>
{% else %}
<div class="card-panel teal lighten-3">
    <span>No hay Turnos actualmente<span>
</div>
{% endif %}

main/templates/profile_for_admin_parts/classrooms.html
<div class="card-content white-text">
    <span class="card-title black-text">Clases</span>
</div>
{% if classrooms %}
<ul class="collapsible">
    {% for classroom in classrooms %}
    <li id="classroom{{ classroom.id }}">
        <div class="collapsible-header">{{ classroom.id }}</div>
        <div class="collapsible-body">
            <div class="row">Descripcion: {{ classroom.description }}</div>
            <div class="row">Duracion: {{ classroom.duration }}</div>
            <div class="row">
                <table>
                    <thead>
                    <tr>
                        <th>Profesor</th>
                        <th>Desmatricular</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for enrolment_teacher in classroom.get_enrolment_teachers %}
                    <tr>
                        <td>{{ enrolment_teacher.person.user.get_full_name }}</td>
                        <td>
                            <button class="btn btn-flat waves-effect waves-grey">clear</i></button>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Dia</th>
                        <th>Hora</th>
                        <th>Lugar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for classroom_day in classroom.get_classroom_days %}
                    <tr>
                        <td>{{ classroom_day.get_day_display }}</td>
                        <td>{{ classroom_day.start_hour }}</td>
                        <td>{{ classroom_day.classroom_place.room }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <ul class="collapsible">
                <li>
                    <div class="collapsible-header">Alumnos</div>
                    <div class="collapsible-body">
                        {% if classroom.get_enrolment_students %}
                            <table>
                                <thead>
                                  <tr>
                                      <th>Nombre</th>
                                      <th>Eliminar</th>
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for enrolment_student in classroom.get_enrolment_students %}
                                    <tr>
                                        <td>{{ enrolment_student.person.user.get_full_name }}</td>
                                        <td><button class="btn btn-flat red-text"><i class="material-icons">clear</i></button></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                        No hay alumnos inscriptos
                        {% endif %}
                    </div>
                </li>
            </ul>
            <center><a class="waves-effect waves-light red btn" onclick="remove('{% url 'delete' 'Classroom' classroom.id %}', 'classroom{{ classroom.id }}')"><i class="material-icons right">delete</i>Eliminar</a></center>
        </div>
    </li>
    {% endfor %}		
</ul>
{% else %}
<div class="card-panel teal lighten-3">
        <span>No hay clases actualmente<span>
</div>
{% endif %}

main/templates/profile_for_retired.html
{% extends 'mainBase.html' %}
{% load static %}
{% block imports %}
{% endblock imports %}
{% block title %}
Perfil retirado
{% endblock title %}  
{% block body %}
<div class="row">   
    <div class="col s12 xl6">
        <ul class="collection with-header">
            <li class="collection-header grey lighten-3"><h4>Turnos</h4></li>
            <li class="collection-item">
                {% if appointments %}
                <table>
                    <thead>
                        <tr>
                            <th>Doctor</th>
                            <th>Hora de atencion</th>
                            <th>Cancelar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for appointment in appointments %}
                        <tr>
                            <td>{{ appointment.work_day.doctor.user.get_full_name }}</td>
                            <td>{{ appointment.time_attendance }}</td>
                            <td><button class="btn btn-flat red-text" onclick="confirm_request('{{ appointment.id }}', '{% url 'appointment_requests' %}', '0')"><i class="material-icons">clear</i></button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                No tienes turnos pendientes
                {% endif %}
            </li>
            <li class="collection-item center-align">
                <a href="{% url 'appointments' %}" class="btn btn-flat red white-text">Solicitar nuevos turnos</a>
            </li>
        </ul>
    </div>
    <div class="col s12 xl6">
        <ul class="collection with-header">
            <li class="collection-header grey lighten-3"><h4>Clases</h4></li>
            <li class="collection-item">
                {% if enrolments %}
                <table>
                    <thead>
                        <tr>
                            <th>Profesores</th>
                            <th>Dias</th>
                            <th>Duracion</th>
                            <th>Salon</th>
                            <th>Cancelar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for enrolment in enrolments %}
                        <tr>
                            <td>
                                {% for teacher in enrolment.classroom.get_teachers %} 
                                    <div>
                                        {{ teacher.person.user.get_full_name }} 
                                    </div>
                                {% endfor %}
                            </td>
                            <td>
                                {% for day in enrolment.classroom.get_classroom_days %} 
                                    <div>
                                        {{ day.get_day_display }} - {{ day.start_hour }}
                                    </div>
                                {% endfor %}
                            </td>
                            <td>{{ enrolment.classroom.duration }}</td>
                            <td>{{ enrolment.classroom.get_next_day.classroom_place.room }}</td>
                            <td><button class="btn btn-flat red-text" onclick="my_ajax('{{ enrolment.id }}', '{% url 'delete_object' %}', 'enrolment_student', '{% url 'profile' %}')"><i class="material-icons">clear</i></button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                No estas matriculado a ninguna clase
                {% endif %}
            </li>
            <li class="collection-item center-align">
                <a href="{% url 'classrooms' %}" class="btn btn-flat red white-text">Solicitar unirse a nuevas clases</a>
            </li>
        </ul>
    </div>
</div>
{% endblock body %}  

main/templates/profile_for_teacher.html
{% extends 'mainBase.html' %}
{% load static %}
{% block imports %}
{% endblock imports %}
{% block title %}
Perfil profesor
{% endblock title %}  
{% block body %}
<div class="row">
    <div class="col s12 xl4">
            <ul class="collection with-header">
                <li class="collection-header"><h4>Perfil</h4></li>
                <li class="collection-item">
                    <div >
                        Nombre: {{ person.user.get_full_name |title }}
                    </div>
                    <div>
                        Dni: {{ person.user }}
                    </div>
                </li>
                <li class="collection-item">
                    <center>    
                        {% if boolean == True %}
                        <button class="btn btn-flat waves-effect waves-grey" onclick="load_solo('{% url 'form_classroom' %}', 'classroom_form')">Crear nueva clase</button>

                        <button class="btn btn-flat waves-effect waves-grey" onclick="load_solo('{% url 'new_enrolment_classroom' %}', 'classroom_form')">Unirse a una clase</button>
                        {% else %}
                        <div class="row  "> 
                            <a class=" red-text s12"> <i class="material-icons left"> block</i>  Usted ya esta asignado una clase <i class="material-icons right"> block</i></a>
                        </div>
                        
                        {% endif %}
                    </center>
                </li>
            </ul>
        <div id="classroom_form">
            <!-- create/modify classroom -->
        </div>
    </div>
    <div class="col s12 xl8">
        {% for enrolment in enrolments %}
        <ul class="collection with-header">
            <li class="collection-header"><h4>{{ enrolment.classroom.name }}</h4></li>
            <li class="collection-item">
                <div>
                    Descripcion: {{ enrolment.classroom.description }}
                </div>
                <div>
                    Duracion: {{ enrolment.classroom.duration }}
                </div>
                <div>                    
                    <table>
                        <thead>
                            <tr>
                                <th>Dia</th>
                                <th>Salon</th>
                                <th>Hora de inicio</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for day in enrolment.classroom.get_classroom_days %}
                            <tr>
                                <td>{{ day.get_day_display }}</td>
                                <td>{{ day.classroom_place.room }}</td>
                                <td>{{ day.start_hour }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </li>
            <li class="collection-item">
                <center>    
                    <button class="btn btn-flat waves-effect waves-grey" onclick="my_ajax('{{ enrolment.id }}', '{% url 'delete_object' %}', 'enrolment_teacher', '{% url 'profile' %}')">Eliminar clase</button>
                    <button class="btn btn-flat waves-effect waves-grey" onclick="load_form_data('{% url 'load_classroom_data' %}', 'classroom_form', '{{ enrolment.classroom.id }}')">Modificar clase</button>
                </center>
            </li>
        </ul>
        {% endfor %}
    </div>
</div>
{% endblock body %}  